@startuml Code Flow Diagram

!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia/puml-theme-materia.puml

title Basic Code Flow Diagram

start

:Hook is Registed for AppointmentBookingFlowPage;

:AppointmentBookingFlowPage;

note right
Query: AppointmentBookingFlowPageQuery
end note

if(Any Location available?) then (yes)

:AppointmentBookingFlowMaster;

:useAppointmentBookingFlow;

-> Object returned from useAppointmentBookingFlow is being passed in the following components;

note right
It returns Data from the query stored in variable named value, an empty state and functions: save, loading and reset.
end note

switch()

case ()
  :Header;
  :Allow booking from Booking Portal;
case () 
  :Sequence;
  :Select Booking Sequence;
case ()
  :Steps;
    ->Based on the booking sequence, Service, employee and availability order will be changed;
  split
  :Service;
  split again
  :Employee;
  split again
  :Availability;
  split again
  :Resource;
  split again
  :Customer;
  split again
  :Cart;
  split again
  :Confirmation;
end split

endswitch

elseif (No active location)
:Show Location Empty State;
end

else (error)
:Error;
end

endif

if(values changed?) then(yes)

split
:Save;

note left
Mutations in this step: UpsertAppointmentBookingFlowSettingMutation and UpsertServiceSettingMutation
end note

end

split again
:Reset;
end
end split

else (no)
end


@enduml